---
Organizations:
    - &OrdererOrg
      Name: OrdererOrg
      ID: OrdererMSP
      MSPDir: crypto-config/ordererOrganizations/example.com/msp
      Policies:
          Readers:
              Type: Signature
              Rule: "OR('OrdererMSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('OrdererMSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('OrdererMSP.admin')"

    - &Central_Government
      Name: CentralGovernmentMSP
      ID: CentralGovernmentMSP
      MSPDir: crypto-config/peerOrganizations/central_gov.example.com/msp
      Policies:
          Readers:
              Type: Signature
              Rule: "OR('CentralGovernmentMSP.admin', 'CentralGovernmentMSP.peer', 'CentralGovernmentMSP.client')"
          Writers:
              Type: Signature
              Rule: "OR('CentralGovernmentMSP.admin', 'CentralGovernmentMSP.client')"
          Admins:
              Type: Signature
              Rule: "OR('CentralGovernmentMSP.admin')"

    - &State_Government
      Name: StateGovernmentMSP
      ID: StateGovernmentMSP
      MSPDir: crypto-config/peerOrganizations/state_gov.example.com/msp
      Policies:
          Readers:
              Type: Signature
              Rule: "OR('StateGovernmentMSP.admin', 'StateGovernmentMSP.peer', 'StateGovernmentMSP.client')"
          Writers:
              Type: Signature
              Rule: "OR('StateGovernmentMSP.admin', 'StateGovernmentMSP.client')"
          Admins:
              Type: Signature
              Rule: "OR('StateGovernmentMSP.admin')"

    - &District_Office
      Name: DistrictOfficeMSP
      ID: DistrictOfficeMSP
      MSPDir: crypto-config/peerOrganizations/district_office.example.com/msp
      Policies:
          Readers:
              Type: Signature
              Rule: "OR('DistrictOfficeMSP.admin', 'DistrictOfficeMSP.peer', 'DistrictOfficeMSP.client')"
          Writers:
              Type: Signature
              Rule: "OR('DistrictOfficeMSP.admin', 'DistrictOfficeMSP.client')"
          Admins:
              Type: Signature
              Rule: "OR('DistrictOfficeMSP.admin')"

    - &Ration_shops
      Name: RationshopsMSP
      ID: RationshopsMSP
      MSPDir: crypto-config/peerOrganizations/ration_shops.example.com/msp
      Policies:
          Readers:
              Type: Signature
              Rule: "OR('RationshopsMSP.admin', 'RationshopsMSP.peer', 'RationshopsMSP.client')"
          Writers:
              Type: Signature
              Rule: "OR('RationshopsMSP.admin', 'RationshopsMSP.client')"
          Admins:
              Type: Signature
              Rule: "OR('RationshopsMSP.admin')"

    - &Citizens
      Name: CitizensMSP
      ID: CitizensMSP
      MSPDir: crypto-config/peerOrganizations/citizens.example.com/msp
      Policies:
          Readers:
              Type: Signature
              Rule: "OR('CitizensMSP.admin', 'CitizensMSP.peer', 'CitizensMSP.client')"
          Writers:
              Type: Signature
              Rule: "OR('CitizensMSP.admin', 'CitizensMSP.client')"
          Admins:
              Type: Signature
              Rule: "OR('CitizensMSP.admin')"

Capabilities:
    Channel: &ChannelCapabilities
        V1_4_3: true
        V1_3: false
        V1_1: false
    Orderer: &OrdererCapabilities
        V1_4_2: true
        V1_1: false
    Application: &ApplicationCapabilities
        V1_4_2: true
        V1_3: false
        V1_2: false
        V1_1: false

Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
    OrdererType: solo
    Addresses:
        - orderer.example.com:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB

    Kafka:
        Brokers:
            - 127.0.0.1:9092

    Organizations:

    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

Profiles:
    LEANOrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Central_Government
                    - *State_Government
                    - *District_Office
                    - *Ration_shops
                    - *Citizens
    LEANChannel:
        Consortium: SampleConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Central_Government
                - *State_Government
                - *District_Office
                - *Ration_shops
                - *Citizens
            Capabilities:
                <<: *ApplicationCapabilities