OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Central Government
    Domain: central_gov.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: State Government
    Domain: state_gov.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

      Name: District Office
    Domain: district_office.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

      Name: Ration shops
    Domain: ration_shops.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

      Name: Citizens
    Domain: citizens.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1